export const FETCH_USER = "FETCH_USER";
export const CLEAR_DATA = "CLEAR_DATA";
export const SET_USER_LOADING = "SET_USER_LOADING";
export const SET_USER_DATA = "SET_USER_DATA";

export const AUTHORIZATION_TYPE_ACTION = "AUTHORIZATION";
export const REGISTRATION_TYPE_ACTION = "REGISTRATION";
export const VERIFICATION_TYPE_ACTION = "VERIFICATION";
export const LOGOUT_TYPE_ACTION = "LOGOUT";

export const FETCH_LUNCH_MENU = "FETCH_LUNCH_MENU";
export const SET_LUNCH_MENU = "SET_LUNCH_MENU";
export const SET_LUNCH_MENU_LOADING = "SET_LUNCH_MENU_LOADING";
export const SELECT_LUNCH_MENU = "SELECT_LUNCH_MENU";
export const GET_SELECT_LUNCH_MENU = "GET_SELECT_LUNCH_MENU";
export const SET_SELECT_LUNCH_MENU = "SET_SELECT_LUNCH_MENU";

export const GET_USER_HISTORY_ORDER = "GET_USER_HISTORY_ORDER";
export const SET_USER_HISTORY_ORDER = "SET_USER_HISTORY_ORDER";
export const SET_USER_HISTORY_ORDER_LOADING = "SET_USER_HISTORY_ORDER_LOADING";
export const SET_USER_HISTORY_ORDER_TOTAL_PAGE =
  "SET_USER_HISTORY_ORDER_TOTAL_PAGE";

export const FETCH_DISHES = "FETCH_DISHES";
export const UPDATE_DISH = "UPDATE_DISH";
export const SET_DISHES = "SET_DISHES";
export const SET_DISHES_LOADING = "SET_DISHES_LOADING";

export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const SET_USERS = "SET_USERS";
export const SET_USERS_TOTAL_PAGE = "SET_USERS_TOTAL_PAGE";
export const UPDATE_BALANCE_USER = "UPDATE_BALANCE_USER";
