export const FETCH_USER = "FETCH_USER";
export const CLEAR_DATA = "CLEAR_DATA";
export const SET_USER_LOADING = "SET_USER_LOADING";
export const SET_USER_DATA = "SET_USER_DATA";

export const AUTHORIZATION_TYPE_ACTION = "AUTHORIZATION";
export const REGISTRATION_TYPE_ACTION = "REGISTRATION";
export const VERIFICATION_TYPE_ACTION = "VERIFICATION";
export const LOGOUT_TYPE_ACTION = "LOGOUT_TYPE_ACTION";
